// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_500 from "./routes/_500.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.tsx";
import * as $admin_accounts from "./routes/admin/accounts.tsx";
import * as $admin_edit from "./routes/admin/edit.tsx";
import * as $admin_index from "./routes/admin/index.tsx";
import * as $admin_nodes from "./routes/admin/nodes.tsx";
import * as $api_balance from "./routes/api/balance.tsx";
import * as $api_variables from "./routes/api/variables.ts";
import * as $bot_is_blocked from "./routes/bot-is-blocked.tsx";
import * as $charts_monthly_earnings from "./routes/charts/monthly-earnings.tsx";
import * as $credentials from "./routes/credentials.tsx";
import * as $diffuse from "./routes/diffuse.tsx";
import * as $index from "./routes/index.tsx";
import * as $me_index from "./routes/me/index.tsx";
import * as $me_transactions from "./routes/me/transactions.tsx";
import * as $nodes_delete_indexOrNumber_ from "./routes/nodes/delete/[indexOrNumber].tsx";
import * as $nodes_delete_index from "./routes/nodes/delete/index.tsx";
import * as $nodes_earnings_number_ from "./routes/nodes/earnings/[number].tsx";
import * as $nodes_earnings_index from "./routes/nodes/earnings/index.tsx";
import * as $nodes_earnings_monthly from "./routes/nodes/earnings/monthly.tsx";
import * as $nodes_index from "./routes/nodes/index.tsx";
import * as $nodes_monitor from "./routes/nodes/monitor.tsx";
import * as $nodes_new_confirm from "./routes/nodes/new-confirm.tsx";
import * as $nodes_new from "./routes/nodes/new.tsx";
import * as $nodes_notifications from "./routes/nodes/notifications.tsx";
import * as $signin from "./routes/signin.tsx";
import * as $signout from "./routes/signout.tsx";
import * as $Balance from "./islands/Balance.tsx";
import * as $EarningsTable from "./islands/EarningsTable.tsx";
import * as $EarningsTableAndOptions from "./islands/EarningsTableAndOptions.tsx";
import * as $EditableObject_GetDateInput from "./islands/EditableObject/GetDateInput.tsx";
import * as $LocaleDate from "./islands/LocaleDate.tsx";
import * as $NewConfirmNodeSelector from "./islands/NewConfirmNodeSelector.tsx";
import * as $Nodes_TimeToPay from "./islands/Nodes/TimeToPay.tsx";
import * as $RelativeDate from "./islands/RelativeDate.tsx";
import * as $TimeLeft from "./islands/TimeLeft.tsx";
import * as $Withdraw from "./islands/Withdraw.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_500.tsx": $_500,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.tsx": $_middleware,
    "./routes/admin/accounts.tsx": $admin_accounts,
    "./routes/admin/edit.tsx": $admin_edit,
    "./routes/admin/index.tsx": $admin_index,
    "./routes/admin/nodes.tsx": $admin_nodes,
    "./routes/api/balance.tsx": $api_balance,
    "./routes/api/variables.ts": $api_variables,
    "./routes/bot-is-blocked.tsx": $bot_is_blocked,
    "./routes/charts/monthly-earnings.tsx": $charts_monthly_earnings,
    "./routes/credentials.tsx": $credentials,
    "./routes/diffuse.tsx": $diffuse,
    "./routes/index.tsx": $index,
    "./routes/me/index.tsx": $me_index,
    "./routes/me/transactions.tsx": $me_transactions,
    "./routes/nodes/delete/[indexOrNumber].tsx": $nodes_delete_indexOrNumber_,
    "./routes/nodes/delete/index.tsx": $nodes_delete_index,
    "./routes/nodes/earnings/[number].tsx": $nodes_earnings_number_,
    "./routes/nodes/earnings/index.tsx": $nodes_earnings_index,
    "./routes/nodes/earnings/monthly.tsx": $nodes_earnings_monthly,
    "./routes/nodes/index.tsx": $nodes_index,
    "./routes/nodes/monitor.tsx": $nodes_monitor,
    "./routes/nodes/new-confirm.tsx": $nodes_new_confirm,
    "./routes/nodes/new.tsx": $nodes_new,
    "./routes/nodes/notifications.tsx": $nodes_notifications,
    "./routes/signin.tsx": $signin,
    "./routes/signout.tsx": $signout,
  },
  islands: {
    "./islands/Balance.tsx": $Balance,
    "./islands/EarningsTable.tsx": $EarningsTable,
    "./islands/EarningsTableAndOptions.tsx": $EarningsTableAndOptions,
    "./islands/EditableObject/GetDateInput.tsx": $EditableObject_GetDateInput,
    "./islands/LocaleDate.tsx": $LocaleDate,
    "./islands/NewConfirmNodeSelector.tsx": $NewConfirmNodeSelector,
    "./islands/Nodes/TimeToPay.tsx": $Nodes_TimeToPay,
    "./islands/RelativeDate.tsx": $RelativeDate,
    "./islands/TimeLeft.tsx": $TimeLeft,
    "./islands/Withdraw.tsx": $Withdraw,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
